name: Update Homebrew Formula

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      version:
        description: "Specify the version number ex. (optional, e.g. v3.0.2 )"
        required: false
        default: ""

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Homebrew Repository
        uses: actions/checkout@v3
        with:
          repository: antnsn/homebrew-lexorium
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}

      - name: Determine Version
        id: vars
        run: |
          # Use the release tag name if available, otherwise use the input version
          if [ -n "${{ github.event.release.tag_name }}" ]; then
            VERSION=${{ github.event.release.tag_name }}
          elif [ -n "${{ github.event.inputs.version }}" ]; then
            VERSION=${{ github.event.inputs.version }}
          else
            echo "Error: No release tag or input version provided." >&2
            exit 1
          fi
          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

          # Construct the asset URL
          ASSET_URL="https://github.com/antnsn/Lexorium/releases/download/$VERSION/Lexorium-darwin-arm64-${VERSION#v}.zip"
          echo "ASSET_URL=$ASSET_URL" >> $GITHUB_ENV

      - name: Debug Variables
        run: |
          echo "Release Version: $RELEASE_VERSION"
          echo "Asset URL: $ASSET_URL"
          curl -I "$ASSET_URL"

      - name: Download Release Asset
        run: |
          echo "Downloading from: $ASSET_URL"
          curl -L "$ASSET_URL" -o "release.zip"
          ls -l "release.zip"

      - name: Verify Downloaded File
        run: |
          echo "File size:"
          ls -lh "release.zip"
          echo "First few bytes (hex):"
          head -c 32 "release.zip" | xxd

      - name: Calculate SHA-256 Checksum
        id: checksum
        run: |
          echo "Calculating SHA for downloaded file"
          sha256sum "release.zip" | tee sha256.txt
          echo "SHA256=$(cat sha256.txt | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Update Formula
        run: |
          FORMULA_FILE="Casks/lexorium.rb"
          
          # Update the URL field
          sed -i "s|url \".*\"|url \"https://github.com/antnsn/Lexorium/releases/download/v#{version}/Lexorium-darwin-arm64-#{version}.zip\"|" $FORMULA_FILE
          
          # Update the version field
          sed -i "s/version \".*\"/version \"${RELEASE_VERSION#v}\"/" $FORMULA_FILE
          
          # Update the sha256 field
          sed -i "s/sha256 \".*\"/sha256 \"$SHA256\"/" $FORMULA_FILE

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          git config --global user.name "antnsn"
          git config --global user.email "antonsen.marius@gmail.com"
          git add Casks/lexorium.rb
          git commit -m "Update Homebrew formula to version $RELEASE_VERSION"
          git push
