name: Build and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'app/'

  pull_request:
    branches:
      - main
    paths:
      - 'app/'

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [win32, darwin, linux]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install
        working-directory: app

      - name: Build
        run: npx electron-forge make --arch=x64 --platform=${{ matrix.platform }}
        working-directory: app

      - name: Publish to GitHub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx electron-forge publish --arch=x64 --platform=${{ matrix.platform }}
        working-directory: app
