name: Release

on:
  release:
    types:
      - created

jobs:
  update_formula_version:
    name: Update the Homebrew formula with latest release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      # add build step ...

      - name: Upload MacOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/target/Lexorium-darwin-x64-${{ steps.get_version.outputs.version }}.zip
          asset_name: Lexorium-darwin-x64-${{ steps.get_version.outputs.version }}.zip
          asset_content_type: application/gzip

      - name: Set macOS release SHA 256
        id: shasum-mac-os
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 ./bin/target/Lexorium-darwin-x64-${{ steps.get_version.outputs.version }}.zip | awk '{printf $1}')"
      - uses: naijabx/update-formula-homebrew-action@v1
        with:
          repo: antnsn/lexorium
          tap: antnsn/homebrew-lexorium
          formula: Casks/lexorium.rb
          download-url: https://github.com/antnsn/lexorium/releases/download/${{ steps.get_version.outputs.version }}/Lexorium-darwin-x64-${{ steps.get_version.outputs.version }}.zip
          sha256: xxxxxxxxxxxxx
          commit-message: update Lexorium formula
        env:
          COMMIT_TOKEN: ${{ secrets.COMMIT_TOKEN }}