name: Update Winget

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag (e.g., v3.0.2)'
        required: true
      asset_name:
        description: 'Asset name (e.g., LexoriumSetup.exe)'
        required: true

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: antnsn.Lexorium
          version: ${{ inputs.version }}
          release-tag: ${{ inputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}